version: "3"
services:

  web:
    build: .
    entrypoint: ls -lA
    volumes:
      - ./web-data/:/go/src/app
      - ./config.ini.docker:/go/cmd/writefreely/config.ini
    ports:
      - "8080:8080"
    networks:
      - external_writefreely
      - internal_writefreely
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mariadb:10
    command: mysqld --character-set-server=latin1 --collation-server=latin1_swedish_ci
    environment:
      - MYSQL_DATABASE=writefreely
      - MYSQL_ROOT_PASSWORD=writefreely
    volumes:
      - ./schema.sql:/tmp/schema.sql
      - ./Mariadb/:/var/lib/mysql
    networks:
      - internal_writefreely
    restart: unless-stopped

networks:
  external_writefreely:
  internal_writefreely:
    internal: true
